spring:

  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    hikari:
      username: sa
      password:
      jdbc-url: jdbc:h2:~/test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update