
server:
  port: 8080

spring:
  profiles:
    active: local
    group:
      test: test-data
  web:
    resources:
      add-mappings: false
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    default-property-inclusion: non_null
    time-zone: Asia/Seoul
  datasource:
    hikari:
      connection-timeout: 10000 #10s
      max-lifetime: 300000     #5m
      maximum-pool-size: 30
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        globally_quoted_identifiers: true

  data:
    web:
      pageable:
        default-page-size: 30

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB


  messages:
    basename: messages/messages

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
org:
  jobrunr:
    dashboard:
      enabled: true
    background-job-server:
      enabled: true
